apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-oradb-jvm
  namespace: oracle
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "45s"
    spec:
      containers:
        - image: docker.io/seighman/spring-jdbc-oracle:jvm
          name: spring-oradb-jvm
          resources: {}