apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-oradb-native
  namespace: oracle
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "45s"
    spec:
      containers:
        - image: docker.io/seighman/spring-jdbc-oracle:native
          name: spring-oradb-native
          resources: {}