apiVersion: batch/v1
kind: Job
metadata:
  name: spring-oradb-native
spec:
  template:
    spec:
      containers:
      - name: spring-oradb-natttive
        image: docker.io/seighman/spring-jdbc-oracle:native
      restartPolicy: Never
  backoffLimit: 2
  ttlSecondsAfterFinished: 30