FROM container-registry.oracle.com/os/oraclelinux:8-slim

# IMPORTANT: Change this variable to the IP of your Oracle Database service
ENV ORACLE_HOST=192.168.49.2

COPY target/spring-jdbc-oracle app
ENTRYPOINT ["/app"]

# Build
# For minikube execute: eval $(minikube docker-env)
# docker build -f containers/Dockerfile.native -t localhost/spring-jdbc-oracle:native .